// Generated by CoffeeScript 1.3.3
(function() {

  window.life = {
    logined: false
  };

  if ($("#login_email").val() !== "") {
    window.life.logined = true;
  }

  window.re_url = "";

  window.MenuCtr = function($scope) {};

  window.MoveCtr = function($scope, $http) {
    $scope.add_hisotry = function(id) {
      if (!window.life.logined) {
        return;
      }
      return $http({
        "url": "/move/add_hisotry/" + id + "?r=" + (Math.random()),
        "method": "GET"
      });
    };
    $scope.add_fav = function(id) {
      var txt;
      if (!window.life.logined) {
        $("#login").show();
        $("#login").modal();
        return;
      }
      txt = $("#fav_link").text();
      if ($.trim(txt) === "已收藏") {
        return;
      }
      return $http({
        "url": "/move/add_fav/" + id + "?r=" + (Math.random()),
        "method": "GET"
      }).success(function(data) {
        return $("#fav_link").text("已收藏");
      });
    };
    $scope.plus_score = function(id) {
      if (!window.life.logined) {
        $("#login").show();
        $("#login").modal();
        return;
      }
      return $http({
        "url": "/move/plus_score/" + id + "?r=" + (Math.random()),
        "method": "GET"
      }).success(function(data) {
        return $("#score_" + id).text(data.display_score);
      });
    };
    return $scope.sub_score = function(id) {
      if (!window.life.logined) {
        $("#login").show();
        $("#login").modal();
        return;
      }
      return $http({
        "url": "/move/sub_score/" + id + "?r=" + (Math.random()),
        "method": "GET"
      }).success(function(data) {
        return $("#score_" + id).text(data.display_score);
      });
    };
  };

  window.UserCtr = function($scope, $http) {
    var user_login;
    user_login = function(name) {
      $("#user_name").text(name);
      $("#login,#user_login").hide();
      $("#login").modal("hide");
      $("#user_info").show();
      window.life.logined = true;
      if (window.location.pathname !== "/") {
        return window.location.href = window.location.href;
      }
    };
    $scope.login = function() {
      return $http({
        "url": "/user_login",
        "method": "GET",
        "params": {
          "email": $scope.email,
          "pwd": $scope.pwd
        }
      }).success(function(data) {
        if (data.name !== void 0) {
          user_login(data.name);
        }
        return {
          "else": $("#login_tips").show()
        };
      });
    };
    return $scope.reg = function() {
      if ($scope.r_email === void 0) {
        $scope.valid_email = "不能为空";
        return;
      }
      if ($scope.r_name === void 0) {
        $scope.valid_name = "不能为空";
        return;
      }
      if ($scope.r_pwd === void 0 || $scope.r_pwd === "") {
        $scope.valid_pwd = "不能为空";
        return;
      }
      return $http({
        "url": "/user_reg",
        "method": "GET",
        "params": {
          "email": $scope.r_email,
          "name": $scope.r_name,
          "pwd": $scope.r_pwd
        }
      }).success(function(data) {
        if (data.success !== null) {
          if (data.has) {
            if (data.has === "email") {
              $scope.valid_email = "邮箱已被占用";
            }
            if (data.has === "name") {
              $scope.valid_name = "称呼已被占用";
            }
            if (data.has === "email_valid") {
              $scope.valid_email = "邮箱格式错误";
            }
            return;
          }
          return user_login(data.name);
        }
      });
    };
  };

  window.play = function(url, index, id) {
    $.get("/move/add_history/" + id + "/" + index);
    $("#" + index + "_c").css("color", "red");
    return add_player(url, "true");
  };

  window.add_player = function(url, auto) {
    return $("#player").qvod({
      PlayerArea: "player",
      width: "400",
      height: "300",
      AutoPlay: auto,
      QvodUrl: url
    });
  };

  window.SocialShareButton = {
    openUrl: function(url) {
      window.open(url);
      return false;
    },
    share: function(el) {
      var img, site, title, url;
      site = $(el).data('site');
      title = encodeURIComponent($(el).data('title'));
      img = encodeURIComponent($(el).data("img"));
      url = encodeURIComponent("http://idianying.tv/move/" + ($(el).data("id")));
      switch (site) {
        case "weibo":
          SocialShareButton.openUrl("http://v.t.sina.com.cn/share/share.php?url=" + url + "&pic=" + img + "&title=" + title + "&content=utf-8");
          break;
        case "twitter":
          SocialShareButton.openUrl("https://twitter.com/home?status=" + title + ": " + url);
          break;
        case "douban":
          SocialShareButton.openUrl("http://www.douban.com/recommend/?url=" + url + "&title=" + title + "&image=" + img);
          break;
        case "facebook":
          SocialShareButton.openUrl("http://www.facebook.com/sharer.php?t=" + title + "&u=" + url);
          break;
        case "qq":
          SocialShareButton.openUrl("http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=" + url + "&title=" + title + "&pics=" + img);
          break;
        case "tqq":
          SocialShareButton.openUrl("http://share.v.t.qq.com/index.php?c=share&a=index&url=" + url + "&title=" + title + "&pic=" + img);
          break;
        case "baidu":
          SocialShareButton.openUrl("http://apps.hi.baidu.com/share/?url=" + url + "&title=" + title + "&content=");
          break;
        case "kaixin001":
          SocialShareButton.openUrl("http://www.kaixin001.com/rest/records.php?url=" + url + "&content=" + title + "&style=11&pic=" + img);
          break;
        case "renren":
          SocialShareButton.openUrl("http://widget.renren.com/dialog/share?resourceUrl=" + url + "&title=" + title + "&description=");
          break;
        case "google_plus":
          SocialShareButton.openUrl("https://plus.google.com/share?url=" + url + "&t=" + title);
          break;
        case "google_bookmark":
          SocialShareButton.openUrl("https://www.google.com/bookmarks/mark?op=edit&output=popup&bkmk=" + url + "&title=" + title);
      }
      return false;
    }
  };

}).call(this);
