source 'http://rubygems.org'
gem 'rspec'
gem 'rspec-mocks'
gem 'second_level_cache', :git => 'git://github.com/csdn-dev/second_level_cache.git' , :branch => "master"
gem 'anemone'
gem 'mongo'
gem 'bson'
gem 'bson_ext'
gem 'activerecord'
gem 'rake'
gem 'activerecord-postgres-hstore', git: 'git://github.com/softa/activerecord-postgres-hstore.git'
gem 'rack-fiber_pool',  :require => 'rack/fiber_pool'
gem 'em-synchrony', :git     => 'git://github.com/igrigorik/em-synchrony.git',
                    :require => ['em-synchrony',
                                                     'em-synchrony/activerecord']
