require 'active_record'
require 'yaml'
require 'logger'
require '../life_lib_ruby/tools.rb'
include Tools
task :test do 
  system("spec test/move_spec.rb --format specdoc")
  system("spec test/user_spec.rb --format specdoc")
end

task :migrate
desc "Migrate the database through scripts in db/migrate. Target specific version with VERSION=x"
task :migrate => :environment do
  ActiveRecord::Migrator.migrate('db/migrate', ENV["VERSION"] ? ENV["VERSION"].to_i : nil )
  
end


task :environment do
  ActiveRecord::Base.establish_connection(get_config("./config.yaml")["PG"])
  ActiveRecord::Base.logger = Logger.new(File.open('./database.log', 'a'))
end

